services:
  - type: web
    name: bra-vibe-api
    runtime: docker
    plan: free
    region: ohio
    dockerContext: .
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8001
      - key: RAPIDAPI_PROXY_SECRET
        generateValue: true # Generates a random secret for you
    autoDeploy: true
